package io.github.jobs.spring.metric;

import io.github.jobs.application.LogRepository;
import io.github.jobs.application.TraceRepository;
import io.github.jobs.infrastructure.InMemoryLogRepository;
import io.github.jobs.infrastructure.InMemoryTraceRepository;
import io.github.jobs.spring.log.LogEntryFactory;
import io.micrometer.core.instrument.Gauge;
import io.micrometer.core.instrument.MeterRegistry;
import io.micrometer.core.instrument.Tags;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import jakarta.annotation.PostConstruct;

/**
 * Exposes internal J-Obs metrics via Micrometer.
 * <p>
 * Metrics exposed:
 * <ul>
 *   <li>jobs.logs.stored - Number of log entries in repository</li>
 *   <li>jobs.logs.buffer.capacity - Log buffer capacity</li>
 *   <li>jobs.logs.buffer.utilization - Log buffer utilization percentage</li>
 *   <li>jobs.logs.by_level - Log count by level (ERROR, WARN, INFO, DEBUG, TRACE)</li>
 *   <li>jobs.traces.stored - Number of traces in repository</li>
 *   <li>jobs.traces.spans.total - Total spans across all traces</li>
 *   <li>jobs.traces.with_errors - Number of traces with errors</li>
 *   <li>jobs.traces.duration.avg - Average trace duration in ms</li>
 *   <li>jobs.traces.duration.p50 - Median trace duration in ms</li>
 *   <li>jobs.traces.duration.p95 - 95th percentile trace duration in ms</li>
 *   <li>jobs.traces.duration.p99 - 99th percentile trace duration in ms</li>
 *   <li>jobs.factory.pool.size - LogEntryFactory pool size</li>
 *   <li>jobs.factory.ids.generated - Total IDs generated by factory</li>
 * </ul>
 */
public class JObsInternalMetrics {

    private static final Logger log = LoggerFactory.getLogger(JObsInternalMetrics.class);
    private static final String METRIC_PREFIX = "jobs";

    private final MeterRegistry meterRegistry;
    private final LogRepository logRepository;
    private final TraceRepository traceRepository;
    private final LogEntryFactory logEntryFactory;

    public JObsInternalMetrics(
            MeterRegistry meterRegistry,
            LogRepository logRepository,
            TraceRepository traceRepository,
            LogEntryFactory logEntryFactory) {
        this.meterRegistry = meterRegistry;
        this.logRepository = logRepository;
        this.traceRepository = traceRepository;
        this.logEntryFactory = logEntryFactory;
    }

    @PostConstruct
    public void registerMetrics() {
        if (logRepository != null) {
            registerLogMetrics();
        }
        if (traceRepository != null) {
            registerTraceMetrics();
        }
        if (logEntryFactory != null) {
            registerFactoryMetrics();
        }
        log.info("J-Obs internal metrics registered");
    }

    private void registerLogMetrics() {
        // Total logs stored
        Gauge.builder(METRIC_PREFIX + ".logs.stored", logRepository, LogRepository::count)
                .description("Number of log entries stored in J-Obs repository")
                .register(meterRegistry);

        // Buffer capacity and utilization (only for InMemoryLogRepository)
        if (logRepository instanceof InMemoryLogRepository inMemoryRepo) {
            Gauge.builder(METRIC_PREFIX + ".logs.buffer.capacity", inMemoryRepo, InMemoryLogRepository::capacity)
                    .description("J-Obs log buffer capacity")
                    .register(meterRegistry);

            Gauge.builder(METRIC_PREFIX + ".logs.buffer.utilization", inMemoryRepo, repo -> {
                int capacity = repo.capacity();
                if (capacity == 0) return 0.0;
                return (double) repo.count() / capacity * 100.0;
            })
                    .description("J-Obs log buffer utilization percentage")
                    .baseUnit("percent")
                    .register(meterRegistry);
        }

        // Logs by level
        registerLogLevelMetric("ERROR");
        registerLogLevelMetric("WARN");
        registerLogLevelMetric("INFO");
        registerLogLevelMetric("DEBUG");
        registerLogLevelMetric("TRACE");
    }

    private void registerLogLevelMetric(String level) {
        Gauge.builder(METRIC_PREFIX + ".logs.by_level", logRepository, repo -> {
            LogRepository.LogStats stats = repo.stats();
            return switch (level) {
                case "ERROR" -> stats.errorCount();
                case "WARN" -> stats.warnCount();
                case "INFO" -> stats.infoCount();
                case "DEBUG" -> stats.debugCount();
                case "TRACE" -> stats.traceCount();
                default -> 0;
            };
        })
                .description("Number of log entries by level")
                .tags(Tags.of("level", level))
                .register(meterRegistry);
    }

    private void registerTraceMetrics() {
        // Total traces stored
        Gauge.builder(METRIC_PREFIX + ".traces.stored", traceRepository, TraceRepository::count)
                .description("Number of traces stored in J-Obs repository")
                .register(meterRegistry);

        // Stats-based metrics
        Gauge.builder(METRIC_PREFIX + ".traces.spans.total", traceRepository, repo -> {
            TraceRepository.TraceStats stats = repo.stats();
            return stats.totalSpans();
        })
                .description("Total spans across all stored traces")
                .register(meterRegistry);

        Gauge.builder(METRIC_PREFIX + ".traces.with_errors", traceRepository, repo -> {
            TraceRepository.TraceStats stats = repo.stats();
            return stats.errorTraces();
        })
                .description("Number of traces with errors")
                .register(meterRegistry);

        Gauge.builder(METRIC_PREFIX + ".traces.duration.avg", traceRepository, repo -> {
            TraceRepository.TraceStats stats = repo.stats();
            return stats.avgDurationMs();
        })
                .description("Average trace duration")
                .baseUnit("milliseconds")
                .register(meterRegistry);

        Gauge.builder(METRIC_PREFIX + ".traces.duration.p50", traceRepository, repo -> {
            TraceRepository.TraceStats stats = repo.stats();
            return stats.p50DurationMs();
        })
                .description("Median trace duration (50th percentile)")
                .baseUnit("milliseconds")
                .register(meterRegistry);

        Gauge.builder(METRIC_PREFIX + ".traces.duration.p95", traceRepository, repo -> {
            TraceRepository.TraceStats stats = repo.stats();
            return stats.p95DurationMs();
        })
                .description("95th percentile trace duration")
                .baseUnit("milliseconds")
                .register(meterRegistry);

        Gauge.builder(METRIC_PREFIX + ".traces.duration.p99", traceRepository, repo -> {
            TraceRepository.TraceStats stats = repo.stats();
            return stats.p99DurationMs();
        })
                .description("99th percentile trace duration")
                .baseUnit("milliseconds")
                .register(meterRegistry);
    }

    private void registerFactoryMetrics() {
        Gauge.builder(METRIC_PREFIX + ".factory.pool.size", logEntryFactory, LogEntryFactory::getPoolSize)
                .description("LogEntryFactory pool size")
                .register(meterRegistry);

        Gauge.builder(METRIC_PREFIX + ".factory.ids.generated", logEntryFactory, LogEntryFactory::getIdCount)
                .description("Total IDs generated by LogEntryFactory")
                .register(meterRegistry);
    }
}
